#!/bin/bash

id=$(echo "$1" | rev | cut -d "/" -f 1 | rev)
url='https://twitter.com/i/videos/tweet/'$id
html=$(curl -Ss "$url" | grep "mp4")
# this probably won't always work
# shellcheck disable=1003
cut=$(echo "$html" | cut -d ";" -f 8 | tr -d '\' | rev | cut -c 6- | rev)
file="$(uuidgen).mp4"
curl -Ss -o "$file" "$cut"
echo "$file"
mv "$file" ~/inbox
