#!/usr/bin/env bash

# this requires the WEIGHTFILE environment variable to be set

if [ $# -ne 1 ]; then
	less "$WEIGHTFILE"
else
	{
		date "+%Y.%m.%d%n%T"
		echo "$1"
		echo ""
	} >>"$WEIGHTFILE"
fi
